### ISSUE TITLE
Issue with Rop and Rope Handler interaction

### ISSUE THREAD

**Issue by MudkipWorld** [mphe/GDNative-Ropesim#9] opened 2024-06-20 11:24 UTC
Hi, I found this add-on and it is very interesting, but when I tried one of the main features I was hoping to work well the most.. It seems somewhat broken.
Example : 
![Rope Issue](https://github.com/mphe/GDNative-Ropesim/assets/94318023/356403c6-a06d-4b06-b3c5-9aff2424ffd2)

Basically the connected part of the rope and handler are very much detach, I have tried fixing this myself by making my own custom handler, but the issue seems to come from the rope itself and I have no idea how to fix it.
By any chance will this get fixed?

**Comment by mphe** [comment] 2024-06-20 14:45
This is actually not a bug but expected behavior.
The handle just sets the point of the rope to its current position every frame.
The rope simulation algorithm proceeds to handle the rope in the same way as usual without regard to handles.
If you set the handle point somewhere inside the rope instead of the end, you will also notice how it doesn't snap 100% towards the handle.

There is currently no support for completely fixating points at certain positions.
I agree this might be a little confusing, but `RopeHandle`s were intended to be a simple solution for animating and deforming ropes with good-enough accuracy.

**Comment by MudkipWorld** [comment] 2024-06-21 08:15
Ah, I see! Makes more sense now.
Thanks for the answer

**Comment by mphe** [comment] 2024-06-21 09:43
I will leave the issue open, because technically it is an issue that can be fixed.

**Comment by mphe** [comment] 2024-07-16 11:45
I've been working on an efficient way to completely fixate points.
You can try out on the [endpoint_fixation](https://github.com/mphe/GDNative-Ropesim/tree/endpoint_fixation) branch or download a build from the [latest build workflow](https://github.com/mphe/GDNative-Ropesim/actions/runs/9946627016).
There is now a `strenght` property in `RopeHandle` to control how strong a point is pulled to the handle's position. A strength of 1.0 will completely fixate the point without gaps.
The new version also includes much more example scenes.
It is not yet merged into `master` but I plan to do so in near future.

**Comment by MudkipWorld** [comment] 2024-07-16 17:02
Thank you so much for your hard work! Happy to hear you were able to fix it (even if it was in a different branch). If you feel like this issue had been solved, I don't mind if it got closed. Again thanks for your work :D

**Comment by mphe** [comment] 2024-07-23 21:19
Closed by #12.
If you find any issues, feel free to use the issue tracker.
I'll create an asset store release in the next days.

**Closed** 2024-07-23 21:19 UTC
